# tentukan role | Sudoer -> role user (bos)
sudo: required

# OS yang mau dipake
# OS -> precies, trusty, xenial
dist: trusty

# bahasa yang digunakan
language: php

# Versi Bahasa yang digunakan
php:
  - 7.1

# tentukan branch
branches:
  only:
    - master #-> QA/Staging
    - develop #-> DevServer

# jalankan install package dll
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

# script -> main excution
script:
  - ./vendor/bin/phpunit
  
# ketika kondisi main execution finish
after_success: